-- 코드를 작성해주세요
# 3세대 대장균 ID
# 대장균 ID 오름차순
# INNER JOIN

SELECT A.ID
FROM ECOLI_DATA A
JOIN ECOLI_DATA B ON B.ID = A.PARENT_ID
JOIN ECOLI_DATA C ON C.ID = B.PARENT_ID
WHERE C.PARENT_ID IS NULL
ORDER BY A.ID