# 2022-04-13 취소되지 않은 흉부외과 진료 예약 내역 조회
# 진료예약일시 기준 오름차순

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P
JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE APNT_YMD LIKE '2022-04-13%'
 AND A.APNT_CNCL_YN = 'N'
 AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;